"""Created RelayGuard initial schema."""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="disabled", nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('disabled', 'active', 'paused')",
            name=op.f("ck_integrations_integration_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("name", name=op.f("uq_integrations_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_integrations_slug")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_users_user_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("audit_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_actor_id_created_at",
        "audit_logs",
        ["actor_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_resource_type_resource_id_created_at",
        "audit_logs",
        ["resource_type", "resource_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_sessions_token_hash")),
    )
    op.create_table(
        "downstream_destinations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("endpoint_url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="disabled", nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'disabled', 'paused')",
            name=op.f("ck_downstream_destinations_downstream_destination_status"),
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_downstream_destinations_integration_id_integrations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_downstream_destinations")),
        sa.UniqueConstraint(
            "integration_id", "name", name="uq_downstream_destinations_integration_id_name"
        ),
    )
    op.create_table(
        "event_schemas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_event_schemas_integration_id_integrations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_schemas")),
        sa.UniqueConstraint(
            "integration_id", "version", name="uq_event_schemas_integration_id_version"
        ),
    )
    op.create_table(
        "simulation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("input_document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name=op.f("ck_simulation_runs_simulation_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_simulation_runs_integration_id_integrations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_simulation_runs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_runs")),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_roles_user_id_role_id"),
    )
    op.create_table(
        "webhook_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="received", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("query_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_body_hash", sa.String(length=255), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('received', 'accepted', 'rejected')",
            name=op.f("ck_webhook_receipts_webhook_receipt_status"),
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_webhook_receipts_integration_id_integrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_receipts")),
    )
    op.create_table(
        "webhook_secrets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("secret_hash", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'expired')",
            name=op.f("ck_webhook_secrets_webhook_secret_status"),
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_webhook_secrets_integration_id_integrations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_secrets")),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=True),
        sa.Column("deduplication_key", sa.String(length=255), nullable=False),
        sa.Column("source_event_id", sa.String(length=255), nullable=True),
        sa.Column("event_type", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="accepted", nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('accepted', 'processing', 'delivered', 'failed', 'dead_lettered')",
            name=op.f("ck_events_event_status"),
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_events_integration_id_integrations"),
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["webhook_receipts.id"],
            name=op.f("fk_events_receipt_id_webhook_receipts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint(
            "integration_id", "deduplication_key", name="uq_events_integration_id_deduplication_key"
        ),
    )
    op.create_index(
        "ix_events_integration_id_status_received_at",
        "events",
        ["integration_id", "status", sa.literal_column("received_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_events_received_at", "events", [sa.literal_column("received_at DESC")], unique=False
    )
    op.create_index(
        "uq_events_integration_id_source_event_id_not_null",
        "events",
        ["integration_id", "source_event_id"],
        unique=True,
        postgresql_where=sa.text("source_event_id IS NOT NULL"),
    )
    op.create_table(
        "routing_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("match_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'disabled')", name=op.f("ck_routing_rules_routing_rule_status")
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["downstream_destinations.id"],
            name=op.f("fk_routing_rules_destination_id_downstream_destinations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_routing_rules_integration_id_integrations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routing_rules")),
        sa.UniqueConstraint("integration_id", "name", name="uq_routing_rules_integration_id_name"),
    )
    op.create_table(
        "event_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=False),
        sa.Column("routing_rule_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ("
            "'pending', 'scheduled', 'in_progress', 'succeeded', 'failed', 'dead_lettered'"
            ")",
            name=op.f("ck_event_deliveries_event_delivery_status"),
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["downstream_destinations.id"],
            name=op.f("fk_event_deliveries_destination_id_downstream_destinations"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_deliveries_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["routing_rule_id"],
            ["routing_rules.id"],
            name=op.f("fk_event_deliveries_routing_rule_id_routing_rules"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_deliveries")),
    )
    op.create_index(
        "ix_event_deliveries_status_next_attempt_at",
        "event_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_table(
        "event_payloads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("payload_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_payloads_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_payloads")),
        sa.UniqueConstraint("event_id", name=op.f("uq_event_payloads_event_id")),
    )
    op.create_table(
        "event_state_transitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("transition_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN ("
            "'accepted', 'processing', 'delivered', 'partially_failed', "
            "'dead_lettered', 'cancelled'"
            ")",
            name=op.f("ck_event_state_transitions_event_state_transition_from_status"),
        ),
        sa.CheckConstraint(
            "to_status IN ("
            "'accepted', 'processing', 'delivered', 'partially_failed', "
            "'dead_lettered', 'cancelled'"
            ")",
            name=op.f("ck_event_state_transitions_event_state_transition_to_status"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_state_transitions_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_state_transitions")),
    )
    op.create_table(
        "dead_letter_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("resolution_status", sa.String(length=32), server_default="open", nullable=False),
        sa.Column("severity", sa.String(length=32), server_default="medium", nullable=False),
        sa.Column(
            "dead_lettered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("context_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "resolution_status IN ('open', 'acknowledged', 'resolved')",
            name=op.f("ck_dead_letter_events_dead_letter_event_resolution_status"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_dead_letter_events_dead_letter_event_severity"),
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["event_deliveries.id"],
            name=op.f("fk_dead_letter_events_delivery_id_event_deliveries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dead_letter_events")),
        sa.UniqueConstraint("delivery_id", name=op.f("uq_dead_letter_events_delivery_id")),
    )
    op.create_index(
        "ix_dle_resolution_status_severity_dead_lettered_at",
        "dead_letter_events",
        ["resolution_status", "severity", sa.literal_column("dead_lettered_at DESC")],
        unique=False,
    )
    op.create_table(
        "delivery_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_status_code", sa.Integer(), nullable=True),
        sa.Column("response_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed')",
            name=op.f("ck_delivery_attempts_delivery_attempt_status"),
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["event_deliveries.id"],
            name=op.f("fk_delivery_attempts_delivery_id_event_deliveries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_attempts")),
        sa.UniqueConstraint(
            "delivery_id", "attempt_number", name="uq_delivery_attempts_delivery_id_attempt_number"
        ),
    )
    op.create_table(
        "retry_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'cancelled', 'failed')",
            name=op.f("ck_retry_jobs_retry_job_status"),
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["event_deliveries.id"],
            name=op.f("fk_retry_jobs_delivery_id_event_deliveries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retry_jobs")),
    )
    op.create_index("ix_retry_jobs_status_run_at", "retry_jobs", ["status", "run_at"], unique=False)
    op.create_table(
        "ai_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("delivery_id", sa.UUID(), nullable=True),
        sa.Column("dead_letter_event_id", sa.UUID(), nullable=True),
        sa.Column("analysis_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("detail_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed')",
            name=op.f("ck_ai_analyses_ai_analysis_status"),
        ),
        sa.CheckConstraint(
            "((event_id IS NOT NULL)::integer + "
            "(delivery_id IS NOT NULL)::integer + "
            "(dead_letter_event_id IS NOT NULL)::integer) = 1",
            name=op.f("ck_ai_analyses_ai_analysis_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["dead_letter_event_id"],
            ["dead_letter_events.id"],
            name=op.f("fk_ai_analyses_dead_letter_event_id_dead_letter_events"),
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["event_deliveries.id"],
            name=op.f("fk_ai_analyses_delivery_id_event_deliveries"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_ai_analyses_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analyses")),
    )
    op.create_table(
        "replay_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dead_letter_event_id", sa.UUID(), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("request_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'running', 'completed', 'rejected', 'cancelled')",
            name=op.f("ck_replay_requests_replay_request_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_replay_requests_approved_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["dead_letter_event_id"],
            ["dead_letter_events.id"],
            name=op.f("fk_replay_requests_dead_letter_event_id_dead_letter_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_replay_requests_requested_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_replay_requests")),
    )
    op.create_index(
        "uq_replay_requests_active_dead_letter_event_id",
        "replay_requests",
        ["dead_letter_event_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'approved')"),
    )
    op.create_table(
        "ai_evaluation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ai_analysis_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("evaluation_document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name=op.f("ck_ai_evaluation_runs_ai_evaluation_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_analysis_id"],
            ["ai_analyses.id"],
            name=op.f("fk_ai_evaluation_runs_ai_analysis_id_ai_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_evaluation_runs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_evaluation_runs")
    op.drop_index(
        "uq_replay_requests_active_dead_letter_event_id",
        table_name="replay_requests",
        postgresql_where=sa.text("status IN ('pending', 'approved')"),
    )
    op.drop_table("replay_requests")
    op.drop_table("ai_analyses")
    op.drop_index("ix_retry_jobs_status_run_at", table_name="retry_jobs")
    op.drop_table("retry_jobs")
    op.drop_table("delivery_attempts")
    op.drop_index(
        "ix_dle_resolution_status_severity_dead_lettered_at", table_name="dead_letter_events"
    )
    op.drop_table("dead_letter_events")
    op.drop_table("event_state_transitions")
    op.drop_table("event_payloads")
    op.drop_index("ix_event_deliveries_status_next_attempt_at", table_name="event_deliveries")
    op.drop_table("event_deliveries")
    op.drop_table("routing_rules")
    op.drop_index(
        "uq_events_integration_id_source_event_id_not_null",
        table_name="events",
        postgresql_where=sa.text("source_event_id IS NOT NULL"),
    )
    op.drop_index("ix_events_received_at", table_name="events")
    op.drop_index("ix_events_integration_id_status_received_at", table_name="events")
    op.drop_table("events")
    op.drop_table("webhook_secrets")
    op.drop_table("webhook_receipts")
    op.drop_table("user_roles")
    op.drop_table("simulation_runs")
    op.drop_table("event_schemas")
    op.drop_table("downstream_destinations")
    op.drop_table("auth_sessions")
    op.drop_index("ix_audit_logs_resource_type_resource_id_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_id_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("integrations")
    # ### end Alembic commands ###
